version: '3'

services: 
  portainer:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    container_name: portainer
    restart: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
 
volumes:
  portainer_data:
  
